Feature | New Component SFBadge
Smartforce-Technologies-Inc/sfui pull request #123
Opened 2021-11-04 14:55 UTC by Yopo-Nicolas

2021-11-08 12:30 UTC, pdcastano requested changes

2021-11-08 12:30 UTC, pdcastano commented on src/Components/SFBadge/SFBadge.tsx
> +      anchorOrigin={{ vertical: 'top', horizontal: 'left' }}
This value should be set as the default behavior, not a fixed value.

2021-11-08 12:30 UTC, pdcastano commented on src/Components/SFBadge/SFBadge.tsx
> +      className={`${size}`}
this should have className and size as value.

2021-11-08 12:30 UTC, pdcastano commented on src/Components/SFBadge/SFBadge.tsx
> +    '&.small': {
![image](https://user-images.githubusercontent.com/17514930/140741257-92a660a7-9026-4b16-8a90-8c1d5679fc09.png)
Small badge are not well styled

2021-11-08 14:04 UTC, Yopo-Nicolas commented on src/Components/SFBadge/SFBadge.tsx
> +      anchorOrigin={{ vertical: 'top', horizontal: 'left' }}
changed

2021-11-08 14:04 UTC, Yopo-Nicolas commented on src/Components/SFBadge/SFBadge.tsx
> +      className={`${size}`}
changed

2021-11-08 14:04 UTC, Yopo-Nicolas commented on src/Components/SFBadge/SFBadge.tsx
> +    '&.small': {
fixed layout

2021-11-09 12:23 UTC, pdcastano requested changes

2021-11-09 12:23 UTC, pdcastano commented on src/Components/SFBadge/SFBadge.tsx
> +  badge: {
![image](https://user-images.githubusercontent.com/17514930/140922886-0bd7cea7-ba78-41f2-ad5a-a42a75c9cec8.png)
The badge is not displayed in the correct position.
Check https://mui.com/components/badges/#unstyled to see how it works.

2021-11-09 12:23 UTC, pdcastano commented on src/Components/SFBadge/SFBadge.tsx
> +    <StyledBadge {...props} className={size} badgeContent={BadgeContent()}>
You are missing the SFBadge className prop in this way. You are replacing it with the size value instead.

2021-11-09 15:06 UTC, Yopo-Nicolas commented on src/Components/SFBadge/SFBadge.tsx
> +  badge: {
fixed

2021-11-09 15:06 UTC, Yopo-Nicolas commented on src/Components/SFBadge/SFBadge.tsx
> +    <StyledBadge {...props} className={size} badgeContent={BadgeContent()}>
added

2021-11-10 12:16 UTC, pdcastano requested changes

2021-11-10 12:16 UTC, pdcastano commented on src/Components/SFBadge/SFBadge.tsx
> +  }
Remove this style. As you can see, this applies only for one anchorOrigin position and that is wrong.
On the other side, checking the stories, I think that we will have to adjust the badge position manually in each particular case into the application.

2021-11-10 18:42 UTC, pdcastano commented
LGTM

2021-11-10 18:42 UTC, pdcastano approved these changes

2021-11-10 18:47 UTC, merged