Added isFullWidth prop to SFChipListField
Smartforce-Technologies-Inc/sfui pull request #144
Opened 2022-02-16 14:41 UTC by Yopo-Nicolas

2022-02-16 16:00 UTC, pdcastano requested changes

2022-02-17 14:13 UTC, Yopo-Nicolas commented on src/Components/SFChipsListField/SFChipsListField.tsx
> +  isFullWidth?: boolean;
changed to isInputFullWidth

2022-02-18 17:42 UTC, pdcastano requested changes
The story is not working for the inputMinWidth prop. Try to find a way to solve the issue.

2022-02-18 18:45 UTC, Yopo-Nicolas commented on src/Components/SFChipsListField/SFChipsListField.tsx
> +}
done

2022-02-18 19:47 UTC, pdcastano requested changes

2022-02-18 20:14 UTC, Yopo-Nicolas commented on src/Components/SFChipsListField/SFChipsListField.tsx
> +type minWidthStyle = number | 'auto' | 'full-width';
done

2022-02-21 11:34 UTC, merged