Doc storybook stories
Smartforce-Technologies-Inc/sfui pull request #157
Opened 2022-03-02 15:58 UTC by Yopo-Nicolas

2022-03-02 20:10 UTC, pdcastano requested changes

2022-03-02 20:10 UTC, pdcastano commented on src/Components/SFAlert/SFAlert.stories.tsx
> +        '	Callback fired when the component requests to be closed. When provided a close icon button is displayed that triggers the callback when clicked.',
remove white space before 'Callback'

2022-03-02 20:10 UTC, pdcastano commented on src/Components/SFAlertCollapse/SFAlertCollapse.stories.tsx
> +      defaultValue: 'Lorem ipsum dolor sit amet.'
'Lorem ipsum dolor sit amet.' is not a default value.

2022-03-02 20:10 UTC, pdcastano commented on src/Components/SFAlertDialog/SFAlertDialog.stories.tsx
> +    }}
why this change?

2022-03-02 20:10 UTC, pdcastano commented on src/Components/SFAlertDialog/SFAlertDialog.stories.tsx
> +      }}
why this change?

2022-03-03 12:11 UTC, Yopo-Nicolas commented on src/Components/SFAlert/SFAlert.stories.tsx
> +        '	Callback fired when the component requests to be closed. When provided a close icon button is displayed that triggers the callback when clicked.',
done

2022-03-03 12:11 UTC, Yopo-Nicolas commented on src/Components/SFAlertCollapse/SFAlertCollapse.stories.tsx
> +      defaultValue: 'Lorem ipsum dolor sit amet.'
changed

2022-03-03 12:12 UTC, Yopo-Nicolas commented on src/Components/SFAlertDialog/SFAlertDialog.stories.tsx
> +    }}
This was the linter because of props added while testing

2022-03-03 12:12 UTC, Yopo-Nicolas commented on src/Components/SFAlertDialog/SFAlertDialog.stories.tsx
> +      }}
This was the linter because of props added while testing

2022-03-03 19:46 UTC, pdcastano approved these changes

2022-03-07 15:53 UTC, pdcastano requested changes

2022-03-07 15:55 UTC, Yopo-Nicolas commented on src/Components/SFAlertCollapse/SFAlertCollapse.stories.tsx
> +};
removed

2022-03-07 19:35 UTC, pdcastano approved these changes

2022-03-07 19:35 UTC, pdcastano commented
LGTM

2022-03-07 19:35 UTC, merged