CC-808 | SFUI | SFAutocompleteChip component
Smartforce-Technologies-Inc/sfui pull request #189
Opened 2022-04-11 15:10 UTC by Yopo-Nicolas

2022-04-13 14:06 UTC, martinweingart requested changes
Need changes

2022-04-13 14:06 UTC, martinweingart commented on src/Components/SFChipsListField/SFChipsListField.tsx
>  const chipsDisplay = makeStyles({
rename to chipsDisplayClasses

2022-04-13 14:44 UTC, Yopo-Nicolas commented on src/Components/SFAutocompleteChips/SFAutocompleteChip.stories.tsx
> +      description: 'If true, the chip should be displayed in a disabled state.'
Changed to component

2022-04-13 14:44 UTC, Yopo-Nicolas commented on src/Components/SFAutocompleteChips/SFAutocompleteChip.stories.tsx
> +];
Was done to reutilize items in multiple stories, changed for only one story

2022-04-13 14:44 UTC, Yopo-Nicolas commented on src/Components/SFAutocompleteChips/SFAutocompleteChip.stories.tsx
> +  emptyMessage: 'No movies saved...',
Removed

2022-04-13 14:45 UTC, Yopo-Nicolas commented on src/Components/SFAutocompleteChips/SFAutocompleteChip.tsx
> +export const SFAutocompleteChip = ({
Changed parent folder name

2022-04-13 14:45 UTC, Yopo-Nicolas commented on src/Components/SFAutocompleteChips/SFAutocompleteChip.tsx
> +  const deleteValue = (input: string): void => {
Renamed

2022-04-13 14:45 UTC, Yopo-Nicolas commented on src/Components/SFAutocompleteChips/SFAutocompleteChip.tsx
> +  };
Removed

2022-04-13 14:46 UTC, Yopo-Nicolas commented on src/Components/SFAutocompleteChips/SFAutocompleteChip.tsx
> +    }
Removed unused code

2022-04-13 16:15 UTC, Yopo-Nicolas commented on src/Components/SFAutocompleteChips/SFAutocompleteChip.tsx
> +          <SFAutocompleteChipRender values={value} onDelete={deleteValue} />
done

2022-04-13 18:19 UTC, martinweingart approved these changes
LGTM

2022-04-18 11:50 UTC, pdcastano requested changes
Disable = true allows remove chips options

2022-04-18 13:57 UTC, pdcastano commented
LGTM

2022-04-18 13:58 UTC, pdcastano approved these changes

2022-04-18 13:58 UTC, merged