Feature SFSnackBar component
Smartforce-Technologies-Inc/sfui pull request #199
Opened 2022-06-10 19:33 UTC by Yopo-Nicolas

2022-06-13 14:31 UTC, pdcastano requested changes

2022-06-15 14:17 UTC, Yopo-Nicolas commented on src/Components/SFSnackbar/SFSnackbar.tsx
> +  message: string;
Changed

2022-06-15 14:17 UTC, Yopo-Nicolas commented on src/Components/SFSnackbar/SFSnackbar.tsx
> +  open = true,
Done

2022-06-23 16:43 UTC, pdcastano requested changes
* background-color and box-shadow props don't match with Figma (DM/NM)

2022-06-23 19:06 UTC, pdcastano requested changes

2022-06-24 12:27 UTC, Yopo-Nicolas commented on src/Components/SFSnackbar/SFSnackbar.tsx
> +}: SFSnackBarProps): React.ReactElement<SFSnackBarProps> => {
done

2022-06-27 11:36 UTC, pdcastano reviewed
Hover and Click styles in the action button are wrong in night mode. (Check also colors in day mode)

2022-06-27 19:56 UTC, pdcastano commented
LGTM

2022-06-27 19:56 UTC, merged