Feature | Added SFCounter component
Smartforce-Technologies-Inc/sfui pull request #231
Opened 2023-02-01 19:50 UTC by Yopo-Nicolas

2023-02-02 17:37 UTC, pdcastano requested changes

2023-02-02 17:37 UTC, pdcastano commented on src/Components/SFCounter/SFCounter.tsx
> +  };
Split this logic into two methods `onIncrement` and `onDecrement`

2023-02-02 17:37 UTC, pdcastano commented on src/Components/SFCounter/SFCounter.tsx
> +      </div>
This could be a sub-component SFCounterButton. and should be used for '-' and '+' buttons

2023-02-02 17:37 UTC, pdcastano commented on src/Components/SFNumericField/SFNumericField.tsx
> +  allowNegative = true,
Did you check the default value for this prop in the SFTextField.inputProps object? we should keep it as the default value.

2023-02-02 18:23 UTC, Yopo-Nicolas commented on src/Components/SFNumericField/SFNumericField.tsx
> +  allowNegative = true,
done

2023-02-02 18:24 UTC, Yopo-Nicolas commented on src/Components/SFCounter/SFCounter.tsx
> +      </div>
done

2023-02-02 18:24 UTC, Yopo-Nicolas commented on src/Components/SFCounter/SFCounter.tsx
> +  };
Done

2023-02-02 19:55 UTC, pdcastano requested changes

2023-02-02 19:55 UTC, pdcastano commented on src/Components/SFCounter/SFCounterButton/SFCounterButton.tsx
> +    </div>
`classes.button` class should always be applied and `classes.buttonDisabled` should overwrite those styles.

2023-02-02 20:22 UTC, pdcastano requested changes
There are general issues with the component size fixed where the border sizes didn't were included for computing the height and width values. 
Let's talk about it.

2023-02-02 20:22 UTC, pdcastano commented on src/Components/SFCounter/SFCounter.tsx
> +      height: '46px',
it should be `height:'44px'`

2023-02-03 13:08 UTC, Yopo-Nicolas commented on src/Components/SFCounter/SFCounter.tsx
> +    onChange(newValue < 0 ? 0 : newValue);
Changed

2023-02-03 13:08 UTC, Yopo-Nicolas commented on src/Components/SFCounter/SFCounterButton/SFCounterButton.tsx
> +    </div>
Done

2023-02-03 13:08 UTC, Yopo-Nicolas commented on src/Components/SFCounter/SFCounter.tsx
> +      height: '46px',
Done, changed to 42px

2023-02-03 13:42 UTC, pdcastano requested changes

2023-02-03 13:42 UTC, pdcastano commented on src/Components/SFCounter/SFCounterButton/SFCounterButton.tsx
> +      onClick={disabled ? undefined : onClick}
Does it necessary now that the pointer-events: none prop has been added?

2023-02-03 13:42 UTC, pdcastano commented on src/Components/SFCounter/SFCounterButton/SFCounterButton.tsx
> +  icon: string;
It could be a little more specific type`icon = 'Add' | 'Remove'`. It's a better approach because the icon prop is used to add or remove styles and not only for setting the icon element.

2023-02-03 13:55 UTC, Yopo-Nicolas commented on src/Components/SFCounter/SFCounterButton/SFCounterButton.tsx
> +      onClick={disabled ? undefined : onClick}
Removed conditional

2023-02-03 13:55 UTC, Yopo-Nicolas commented on src/Components/SFCounter/SFCounterButton/SFCounterButton.tsx
> +  icon: string;
Done

2023-02-03 14:08 UTC, pdcastano approved these changes

2023-02-03 14:08 UTC, pdcastano commented
LGTM

2023-02-03 14:09 UTC, merged