XX 149  | SFButton Migration
Smartforce-Technologies-Inc/sfui pull request #259
Opened 2023-04-18 14:54 UTC by Yopo-Nicolas

2023-04-25 19:56 UTC, pdcastano requested changes
- disabled style is wrong
- invertedGrey color styles look wrong.

2023-04-26 15:50 UTC, pdcastano requested changes
- In `outlined` and `contained` button variants the text is in uppercase

2023-04-26 15:50 UTC, pdcastano commented on src/Components/SFButton/CustomButtons/ButtonMixin.tsx
>  export default function ButtonMixin(sfButtonConfig: ButtonMixinProps): any {
Is there any way to fix this missed type?

2023-04-26 16:52 UTC, Yopo-Nicolas commented on src/Components/SFButton/CustomButtons/ButtonMixin.tsx
>  export default function ButtonMixin(sfButtonConfig: ButtonMixinProps): any {
This return type is due to MUI styled function returns generic return types. It's done this way to style any component.

2023-04-27 12:07 UTC, pdcastano requested changes

2023-04-27 12:07 UTC, pdcastano commented on src/Components/SFButton/CustomButtons/ButtonMixin.tsx
> +          sfButtonConfig.contained[theme.palette.mode].backgroundColorHover
`:focus` should be replaced with `':focus-visible` as we've defined in the FE meeting.

2023-04-27 12:07 UTC, pdcastano commented on src/Components/SFButton/CustomButtons/ButtonMixin.tsx
> +          sfButtonConfig.contained[theme.palette.mode].backgroundColorHover
Apply this in the whole file

2023-04-27 12:32 UTC, Yopo-Nicolas commented on src/Components/SFButton/CustomButtons/ButtonMixin.tsx
> +          sfButtonConfig.contained[theme.palette.mode].backgroundColorHover
Done

2023-04-28 16:48 UTC, pdcastano approved these changes

2023-04-28 16:49 UTC, pdcastano commented
LGTM

2023-04-28 16:49 UTC, merged