Migrate SFTextField component
Smartforce-Technologies-Inc/sfui pull request #261
Opened 2023-04-19 17:39 UTC by martinweingart

2023-04-26 16:03 UTC, pdcastano requested changes
- 'hover' event styles on the Textfield component with disabled status shouldn't be applied. (Textfield border styles changed)

2023-04-27 12:40 UTC, martinweingart commented
> * 'hover' event styles on the Textfield component with disabled status shouldn't be applied. (Textfield border styles changed)

The hover styles are fine, the default border color it's wrong because the mui lib is overwriting it

2023-04-28 16:52 UTC, pdcastano approved these changes

2023-04-28 16:53 UTC, pdcastano commented
LGTM

2023-04-28 16:53 UTC, merged