Add onClick event to story and fix on click styles
Smartforce-Technologies-Inc/sfui pull request #262
Opened 2023-04-19 17:45 UTC by martinweingart

2023-04-25 19:03 UTC, pdcastano requested changes

2023-04-26 10:39 UTC, martinweingart commented on src/Components/SFIconButton/SFIconButton.tsx
> -    '&:hover, &:focus': {
Because when you click on the button, it remains clicked unless you click in somewhere else

2023-04-28 16:54 UTC, pdcastano commented
LGTM

2023-04-28 16:54 UTC, pdcastano approved these changes

2023-04-28 16:54 UTC, merged