XX 149 | SFChip Migration
Smartforce-Technologies-Inc/sfui pull request #267
Opened 2023-04-25 11:51 UTC by Yopo-Nicolas

2023-07-13 18:27 UTC, martinweingart requested changes

2023-07-17 18:20 UTC, Yopo-Nicolas commented on src/Components/SFChip/SFChip.stories.tsx
Done

2023-07-17 18:20 UTC, Yopo-Nicolas commented on src/Components/SFChip/SFChip.tsx
>      <FormControl fullWidth={fullWidth}>
Removed

2024-01-08 14:45 UTC, martinweingart approved these changes
LGTM

2024-01-08 14:45 UTC, merged