XX 149 | SFRadioGroup
Smartforce-Technologies-Inc/sfui pull request #270
Opened 2023-04-25 14:50 UTC by Yopo-Nicolas

2023-04-26 18:56 UTC, pdcastano requested changes
- Check component props order.

2023-04-26 18:56 UTC, pdcastano commented on src/Components/SFRadioGroup/SFRadio/SFRadio.stories.tsx
>  const Template: Story<SFRadioProps> = (args) => <SFRadio {...args} />;
Update to ComponentStory according to the new Storybook Docs

2023-04-28 17:11 UTC, pdcastano requested changes

2023-04-28 17:11 UTC, pdcastano commented on .storybook/main.js
> +    '../src/Components/SFRadioGroup/*.stories.@(js|jsx|ts|tsx)',
this should be in alphabetic order

2023-04-28 19:35 UTC, Yopo-Nicolas commented on .storybook/main.js
> +    '../src/Components/SFRadioGroup/*.stories.@(js|jsx|ts|tsx)',
Done

2023-05-03 11:49 UTC, pdcastano commented
LGTM

2023-05-03 11:49 UTC, pdcastano approved these changes

2023-05-03 11:50 UTC, merged