XX 169 | SFScrollable migration
Smartforce-Technologies-Inc/sfui pull request #271
Opened 2023-04-25 16:42 UTC by Yopo-Nicolas

2023-04-26 19:10 UTC, pdcastano requested changes

2023-04-26 19:10 UTC, pdcastano commented on src/Components/SFScrollable/SFScrollable.stories.tsx
update to StoryComponent

2023-04-27 11:58 UTC, Yopo-Nicolas commented on src/Components/SFScrollable/SFScrollable.stories.tsx
Done

2023-04-28 17:13 UTC, pdcastano requested changes

2023-04-28 17:13 UTC, pdcastano commented on .storybook/main.js
> +    '../src/Components/SFTimeline/*.stories.@(js|jsx|ts|tsx)',
this should be in alphabetical order

2023-04-28 19:33 UTC, Yopo-Nicolas commented on .storybook/main.js
> +    '../src/Components/SFTimeline/*.stories.@(js|jsx|ts|tsx)',
Done

2023-05-03 19:52 UTC, pdcastano requested changes
Styles seem to be wrong. Scroll bars are blinking (disappearing) while the user is scrolling the content.

2023-07-21 11:17 UTC, martinweingart requested changes

2023-07-21 11:17 UTC, martinweingart commented on src/Components/SFScrollable/ScrollBar/ScrollThumb/ScrollThumb.tsx
> +      style={{ ...getScrollThumbStyles(orientation, spaceLeft, visibleSpace) }}
Set these styles in the `StyledScrollThumb ` function, not as inline styles

2023-07-21 11:17 UTC, martinweingart commented on src/Components/SFScrollable/ScrollBar/ScrollBar.tsx
> +      }}
Set these styles in the `StyledScrollBar`  function, not as inline styles

2023-07-21 11:17 UTC, martinweingart commented on src/Components/SFScrollable/ScrollBar/ScrollBar.tsx
> +  scrollThumbProps: Omit<ScrollThumbProps, 'orientation'>;
It would be better to pass the ScrollThumb as children instead of passing these props

2023-07-21 11:17 UTC, martinweingart commented on src/Components/SFScrollable/SFScrollable.tsx
> +          }}
It's better to add `<ScrollThumb>` as children, instead of passing these props

2023-07-21 11:17 UTC, martinweingart commented on src/Components/SFScrollable/SFScrollable.tsx
> +          }}
It's better to add `<ScrollThumb>` as children, instead of passing these props

2023-07-24 13:16 UTC, Yopo-Nicolas commented on src/Components/SFScrollable/ScrollBar/ScrollThumb/ScrollThumb.tsx
> +      style={{ ...getScrollThumbStyles(orientation, spaceLeft, visibleSpace) }}
Done

2023-07-24 13:16 UTC, Yopo-Nicolas commented on src/Components/SFScrollable/ScrollBar/ScrollBar.tsx
> +      }}
Done

2023-07-24 13:16 UTC, Yopo-Nicolas commented on src/Components/SFScrollable/SFScrollable.tsx
> +          }}
Done

2023-07-24 13:16 UTC, Yopo-Nicolas commented on src/Components/SFScrollable/ScrollBar/ScrollBar.tsx
> +  scrollThumbProps: Omit<ScrollThumbProps, 'orientation'>;
Done

2024-01-09 11:52 UTC, merged