XX 186 | SFSkeleton migration
Smartforce-Technologies-Inc/sfui pull request #272
Opened 2023-04-25 19:04 UTC by Yopo-Nicolas

2023-04-26 19:07 UTC, pdcastano requested changes

2023-04-27 11:42 UTC, Yopo-Nicolas commented on src/Components/SFSkeleton/SFSkeleton.stories.tsx
Done

2023-05-03 19:59 UTC, pdcastano requested changes
Could we check and modify the animation colors? There is a light blue color in the animation effect that doesn't seem to be a color from the defined theme palette.

2023-07-17 14:26 UTC, martinweingart approved these changes
LGTM

2023-07-17 14:27 UTC, merged