XX 195 | SFMedia Migration
Smartforce-Technologies-Inc/sfui pull request #281
Opened 2023-04-27 14:53 UTC by Yopo-Nicolas

2023-04-28 18:35 UTC, pdcastano requested changes

2023-04-28 18:35 UTC, pdcastano commented on src/SFMedia/SFMedia.stories.tsx
Check how was it done in the SFColor component with styled-components for code, container, etc classes.

2023-05-02 14:26 UTC, Yopo-Nicolas commented on src/SFMedia/SFMedia.stories.tsx
Done

2023-05-03 20:00 UTC, pdcastano approved these changes

2023-05-03 20:01 UTC, merged